### ISSUE TITLE
Webhook Error

### ISSUE THREAD

**Issue by brunobrandes** [xVir/api-ai-java-webhook#1]
I want use webhook in api.ai but in my tests I received invalid request.
I received this [webhook-request.txt](https://github.com/xVir/api-ai-java-webhook/files/326604/webhook-request.txt) :-1:  
The [webhook documentation](https://docs.api.ai/docs/webhook) contains other request.

**Comment by xVir** [comment]
Hi, @brunobrandes 
Could you please post full text of the  **webhook-request.txt** here. The link to the file is not working...

Thanks.

**Comment by brunobrandes** [comment]
Hi @xVir ,
Look

``` json
"rs":{  
   "cpf":"00000000000",
   "phone":"31999999999",
   "birthDate":{  
      "calendar":526402800000,
      "exact":true,
      "specifiedTimezone":true,
      "midnight":false,
      "dateTime":false,
      "onlyDate":true,
      "rfcString":"19860906T120000-03:00",
      "hours":12,
      "minutes":0,
      "dayOfWeek":6
   },
   "email":"test@gmail.com"
},
"lifespan":4
},
{  
"name":"email-travel",
"parameters":{  
   "phone":"31999999999",
   "email":"test@gmail.com"
},
"lifespan":5
},
{  
"name":"name-travel",
"parameters":{  
   "name":"bruno brandes",
   "cpf":"00000000000",
   "phone":"31999999999",
   "birthDate":{  
      "calendar":526402800000,
      "exact":true,
      "specifiedTimezone":true,
      "midnight":false,
      "dateTime":false,
      "onlyDate":true,
      "rfcString":"19860906T120000-03:00",
      "hours":12,
      "minutes":0,
      "dayOfWeek":6
   },
   "email":"test@gmail.com"
},
"lifespan":4
},
{  
"name":"phone-travel",
"parameters":{  
   "phone":"31999999999"
},
"lifespan":5
},
{  
"name":"birth-date-travel",
"parameters":{  
   "phone":"31999999999",
   "birthDate":{  
      "calendar":526402800000,
      "exact":true,
      "specifiedTimezone":true,
      "midnight":false,
      "dateTime":false,
      "onlyDate":true,
      "rfcString":"19860906T120000-03:00",
      "hours":12,
      "minutes":0,
      "dayOfWeek":6
   },
   "email":"test@gmail.com"
},
"lifespan":4
}
],
"metadata":{  
"intentId":"84d47dfb-a848-42df-bcd9-edf4a3d59ade",
"webhookUsed":"true",
"intentName":"phone-travel"
},
"fulfillment":{  
"speech":"",
"source":null,
"displayText":null,
"data":null
},
"score":0.3549756133814262
},
"alternateResult":null,
"status":{  
"code":200,
"message":null
},
"asr":null,
"sessionId":null
}
```

**Comment by xVir** [comment]
Hi, @brunobrandes 
Sorry for the late answer.
If you mean this part

```
"asr":null,
"sessionId":null
}
```

we are working on the fix.

Thanks.

**Comment by brunobrandes** [comment]
Helo @xVir
The request not is a valid json.
My application not working serializer the request.
This JSON sample contains invalid properties based in [webhook docs](https://docs.api.ai/docs/webhook).

Look first line

``` json
"rs":{
}
```

This not is a valid [query response](https://docs.api.ai/docs/query#response) :(

I expected receive look something like this

``` json
{
  "id": "cfcbd337-6b66-4393-a6a3-74fc5487cedb",
  "timestamp": "2016-02-16T00:30:13.529Z",
  "result": {
    "source": "agent",
    "resolvedQuery": "hi my name is Sam",
    "action": "greetings",
    "actionIncomplete": false,
    "parameters": {
      "name": "Sam"
    },
    "contexts": [
      {
        "name": "greetings",
        "parameters": {
          "name": "Sam"
        },
        "lifespan": 5
      }
    ],
    "metadata": {
      "intentId": "c251ef97-0c43-404d-bf75-98e806f942be",
      "intentName": "Greetings"
    },
    "fulfillment": {
      "speech": "Hi Sam! How can I help you?"
    }
  }
}
```

**Comment by xVir** [comment]
Hi, @brunobrandes 
Could you please give me some part of your agent. It seems you are using some complex contexts, so I will try to reproduce the problem.

Thanks.

**Comment by brunobrandes** [comment]
@xVir 
How can we do that?
Hand me your email to send the agent .zip?

**Comment by brunobrandes** [comment]
Hello @xVir ... any news?

**Comment by artemgoncharuk** [comment]
@brunobrandes Could you please send your agent info (your account email, agent name) to support@api.ai?

**Comment by artemgoncharuk** [comment]
@brunobrandes 
- Use the latest repo - https://github.com/api-ai/apiai-webhook-sample
- How are you logging this JSON? Is it from Heroku log console?

**Comment by brunobrandes** [comment]
Hello @artemgoncharuk 
I found my problem. My application was not prepared to process JSON chunked.
TransferEncodingChunked = true

Already changed my application and now I get the valid JSON, even if different from the documentation :)

Thank you very much for your attention.

**Comment by fatjackgg** [comment]
@xVir May I know the status of the fix? My project is held up by this missing sessionId. Thank you very much.

**Comment by xVir** [comment]
hi @fatjackgg 
the problem should be fixed now, please check it.

Thanks.
